param(
  [string]$ManifestPath = "roms/sources.json",
  [switch]$SkipHash
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot

function Resolve-RepoPath([string]$pathValue) {
  if ([System.IO.Path]::IsPathRooted($pathValue)) {
    return $pathValue
  }
  return Join-Path $RepoRoot $pathValue
}

function New-DirectoryForFile([string]$filePath) {
  $dir = Split-Path -Path $filePath -Parent
  if ($dir -and -not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
  }
}

$manifestFullPath = Resolve-RepoPath $ManifestPath
$exampleManifestPath = Resolve-RepoPath "roms/sources.example.json"

if (-not (Test-Path -LiteralPath $manifestFullPath)) {
  if (-not (Test-Path -LiteralPath $exampleManifestPath)) {
    throw "Manifest not found: $manifestFullPath and example missing at $exampleManifestPath."
  }

  New-DirectoryForFile $manifestFullPath
  Copy-Item -LiteralPath $exampleManifestPath -Destination $manifestFullPath -Force
  Write-Warning "Created manifest at $manifestFullPath from template. Fill legal URLs and rerun."
  return
}

$manifest = Get-Content -LiteralPath $manifestFullPath -Raw | ConvertFrom-Json
if (-not $manifest.items) {
  throw "Manifest has no items[]"
}

$credits = @()

foreach ($item in $manifest.items) {
  if (-not $item.url -or -not $item.targetPath) {
    throw "Each item requires url and targetPath"
  }

  if ($item.url -match '^https://example\.com/') {
    Write-Warning "Skipping placeholder URL for $($item.id). Update roms/sources.json first."
    continue
  }

  if (-not ($item.url -match '^https://')) {
    throw "Only HTTPS URLs are allowed: $($item.url)"
  }

  $target = Resolve-RepoPath $item.targetPath
  New-DirectoryForFile $target

  Write-Host "Downloading $($item.id) -> $target"
  Invoke-WebRequest -Uri $item.url -OutFile $target -UseBasicParsing

  $actualHash = ""
  if (-not $SkipHash) {
    $actualHash = (Get-FileHash -Algorithm SHA256 -Path $target).Hash
    if ($item.sha256 -and $item.sha256 -notmatch '^OPTIONAL' -and $item.sha256 -notmatch '^REPLACE') {
      if ($actualHash.ToUpper() -ne $item.sha256.ToUpper()) {
        throw "SHA256 mismatch for $($item.id). Expected $($item.sha256), got $actualHash"
      }
    }
  }

  $credits += [pscustomobject]@{
    id = $item.id
    title = $item.title
    targetPath = $item.targetPath
    sourceUrl = $item.url
    sourceAttribution = $item.sourceAttribution
    copyrightHolder = $item.copyrightHolder
    licenseProof = $item.licenseProof
    downloadedAtUtc = (Get-Date).ToUniversalTime().ToString("u")
    sha256 = $actualHash
  }
}

$creditsPath = Resolve-RepoPath "roms/CREDITS.generated.md"
$lines = @(
  "# Download Credits (Generated)",
  "",
  "This file is generated by scripts/download_licensed_assets.ps1 from your legal-source manifest.",
  ""
)

foreach ($c in $credits) {
  $lines += "## $($c.title)"
  $lines += "- ID: $($c.id)"
  $lines += "- Stored At: $($c.targetPath)"
  $lines += "- Source URL: $($c.sourceUrl)"
  $lines += "- Attribution: $($c.sourceAttribution)"
  $lines += "- Copyright Holder: $($c.copyrightHolder)"
  $lines += "- License Proof: $($c.licenseProof)"
  $lines += "- Downloaded (UTC): $($c.downloadedAtUtc)"
  if ($c.sha256) {
    $lines += "- SHA256: $($c.sha256)"
  }
  $lines += ""
}

Set-Content -LiteralPath $creditsPath -Value ($lines -join "`r`n")
Write-Host "Done. Credits written to $creditsPath"
